name: AQM

services:
  aqm-back:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8085:8081"
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 512M
        limits:
          cpus: 1
          memory: 1G
